name: Deploy to Production

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: windows-latest
    steps:
    - name: Download Artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        workflow: development.yml
        branch: develop
        name: WebApp
        path: ${{github.workspace}}/WebApp

    - name: Deploy to IIS
      env:
        IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
        IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
        IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
        IIS_WEBSITE_NAME: ${{ secrets.IIS_WEBSITE_NAME }}
        IIS_WEBSITE_PATH: ${{ secrets.IIS_WEBSITE_PATH }}
      run: |
        $ErrorActionPreference = 'Stop'
        $SecurePassword = ConvertTo-SecureString $env:IIS_SERVER_PASSWORD -AsPlainText -Force
        $Credential = New-Object System.Management.Automation.PSCredential ($env:IIS_SERVER_USERNAME, $SecurePassword)
        
        Set-Item WSMan:\localhost\Client\TrustedHosts -Value $env:IIS_SERVER_COMPUTER_NAME -Force

        $SessionOption = New-PSSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck
        $Session = New-PSSession -ComputerName $env:IIS_SERVER_COMPUTER_NAME -Credential $Credential -Authentication Basic -SessionOption $SessionOption

        Copy-Item -Path "${{github.workspace}}/WebApp/*" -Destination $env:IIS_WEBSITE_PATH -ToSession $Session -Recurse -Force

        Invoke-Command -Session $Session -ScriptBlock {
          Import-Module WebAdministration
          Stop-Website -Name $using:env:IIS_WEBSITE_NAME
          # Run database migrations here if needed
          # Example: Invoke-Sqlcmd -InputFile "migrations.sql" -ServerInstance $using:env:DB_SERVER -Database $using:env:DB_NAME -Username $using:env:DB_USER -Password $using:env:DB_PASSWORD
          Start-Website -Name $using:env:IIS_WEBSITE_NAME
        }

        Remove-PSSession $Session