name: Development CI

on:
  push:
    branches: ['develop']

env:
  DOTNET_VERSION: '6.0.x'
  SOLUTION_FILE: 'DotNetCoreSqlDb.sln'
  DB_SERVER: ${{ secrets.DB_SERVER }}
  DB_NAME: ${{ secrets.DB_NAME }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


jobs:
  build-and-test:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore ${{ env.SOLUTION_FILE }}

    - name: Build
      run: dotnet build ${{ env.SOLUTION_FILE }} --configuration Release --no-restore

    - name: Install EF Core Tools
      run: dotnet tool install --global dotnet-ef

    - name: Generate Migration Script
      run: dotnet ef migrations script -p DotNetCoreSqlDb/DotNetCoreSqlDb.csproj -o migrations.sql -i

    - name: Publish Migration Script
      uses: actions/upload-artifact@v4
      with:
        name: MigrationScript
        path: migrations.sql  

    - name: Run unit tests
      run: dotnet test ${{ env.SOLUTION_FILE }} --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4

    - name: Publish
      run: dotnet publish ${{ env.SOLUTION_FILE }} --configuration Release --no-build --output ${{github.workspace}}/publish

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WebApp
        path: ${{github.workspace}}/publish 